name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build_push:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build -t realsidsun/portfolio . 

      - name: Run and curl
        run: |
          docker run realsidsun/portfolio -p 5000:80 --detach
          curl --head localhost:5000

      - name: Push to Docker Hub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
          docker push realsidsun/portfolio

